_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 95
                - 98
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 84
                - 95
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.10
            "6": 4.51.3
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
ahimsa_weight:
    value: 1
beta:
    value: 0.1
dharma_weight:
    value: 1
disable_dropout:
    value: true
fp16:
    value: true
gradient_accumulation_steps:
    value: 2
learning_rate:
    value: 5e-06
logging_steps:
    value: 1
max_completion_length:
    value: 512
max_prompt_length:
    value: 512
mini_repeat_count:
    value: 2
model:
    value: unsloth/Llama-3.2-1B-Instruct
num_generations:
    value: 2
num_train_epochs:
    value: 3
output_dir:
    value: output/Llama-3.2-1B-Instruct-grpo
per_device_train_batch_size:
    value: 2
scenarios:
    value: data/combined_predibase_updated.jsonl
use_basic_prompt:
    value: false
use_separate_rewards:
    value: false
warmup_steps:
    value: 5
